export interface StyleItem {
  num: number;
  title: string;
  prompt: string;
  images: string[];
  category: string;
}

export const SLIDE_STYLES: StyleItem[] = [
  // 모던 & 웹 (1-10)
  {num:1,title:"벤토 그리드 스타일(모던 웹UI)",prompt:"Bento grid UI layout, tech minimalist design, clean web interface, soft lighting, modern corporate aesthetic, vector flat style, UI/UX --ar 16:9",images:["notion_slide_guide/assets/01_벤토_그리드_스타일_모던_웹UI_1.png","notion_slide_guide/assets/01_벤토_그리드_스타일_모던_웹UI_2.png"],category:"모던 & 웹"},
  {num:2,title:"비즈니스 미니멀 스타일",prompt:"Minimalist timeline infographic, simple flat vector art, clean data visualization, geometric shapes, corporate color palette, white background, highly legible --ar 16:9",images:["notion_slide_guide/assets/02_비즈니스_미니멀_스타일_1.png","notion_slide_guide/assets/02_비즈니스_미니멀_스타일_2.png"],category:"모던 & 웹"},
  {num:5,title:"뉴 모피즘 스타일 (모던 웹사이트)",prompt:"Neumorphic tech schematic, soft UI, drop shadows, subtle gradients, clean tech blueprint, modern app interface, minimalist 3D layout",images:["notion_slide_guide/assets/05_뉴_모피즘_스타일_모던_웹사이트_1.png","notion_slide_guide/assets/05_뉴_모피즘_스타일_모던_웹사이트_2.png"],category:"모던 & 웹"},
  {num:18,title:"플랫 코퍼레이트 일러스트",prompt:"Flat corporate illustration, modern business aesthetic, clean vector art, professional color palette, minimalist design, office场景",images:["notion_slide_guide/assets/18_플랫_코퍼레이트_일러스트_1.png","notion_slide_guide/assets/18_플랫_코퍼레이트_일러스트_2.png"],category:"모던 & 웹"},
  {num:27,title:"SaaS 대시보드 인포그래픽",prompt:"SaaS dashboard infographic, modern web app UI, clean data visualization, metric cards, user analytics, professional tech aesthetic",images:["notion_slide_guide/assets/27_SaaS_대시보드_인포그래픽_1.png","notion_slide_guide/assets/27_SaaS_대시보드_인포그래픽_2.png"],category:"모던 & 웹"},
  {num:33,title:"프리미엄 컨설팅 슬라이드 스타일",prompt:"Premium consulting slide, executive presentation aesthetic, sophisticated professional design, high-end business visuals, luxury corporate feel",images:["notion_slide_guide/assets/33_프리미엄_컨설팅_슬라이드_스타일_1.png","notion_slide_guide/assets/33_프리미엄_컨설팅_슬라이드_스타일_2.png"],category:"모던 & 웹"},
  {num:43,title:"모던 다크 모드 디자인",prompt:"Modern dark mode design, dark UI aesthetic, sleek dark interface, premium dark theme, contemporary dark visual design, sophisticated dark palette",images:["notion_slide_guide/assets/43_모던_다크_모드_디자인_1.png","notion_slide_guide/assets/43_모던_다크_모드_디자인_2.png"],category:"모던 & 웹"},
  {num:48,title:"스위스 그리드 인포디자인",prompt:"Swiss grid info design, international typographic style, strict grid system, organized information, clean Swiss design aesthetic, structured layout",images:["notion_slide_guide/assets/48_스위스_그리드_인포디자인_1.png","notion_slide_guide/assets/48_스위스_그리드_인포디자인_2.png"],category:"모던 & 웹"},
  {num:49,title:"포털형 카드 매거진",prompt:"Portal style card magazine, web editorial layout, modular card design, content portal aesthetic, digital magazine format, card-based information hierarchy",images:["notion_slide_guide/assets/49_포털형_카드_매거진_1.png","notion_slide_guide/assets/49_포털형_카드_매거진_2.png"],category:"모던 & 웹"},
  
  // 교육 & 스케치 (11-15)
  {num:3,title:"칠판 스타일 (교육용 슬라이드)",prompt:"Chalkboard sketch, educational diagram, white chalk on dark green board, hand-drawn aesthetic, arrows and mind maps, friendly and approachable tone",images:["notion_slide_guide/assets/03_칠판_스타일_교육용_슬라이드_1.png","notion_slide_guide/assets/03_칠판_스타일_교육용_슬라이드_2.png"],category:"교육 & 스케치"},
  {num:4,title:"일본 종이 만화책 스타일",prompt:"Manga instructional comic panel, clean line art, monochrome with screentones, informative speech bubbles, office worker character, tutorial style, expressive",images:["notion_slide_guide/assets/04_일본_종이_만화책_스타일_1.png","notion_slide_guide/assets/04_일본_종이_만화책_스타일_2.png"],category:"교육 & 스케치"},
  {num:11,title:"식물학/과학 일러스트 스타일",prompt:"Botanical scientific illustration, vintage field guide style, delicate line work, watercolor shading, highly detailed and precise",images:["notion_slide_guide/assets/11_식물학_과학_일러스트_스타일_1.png","notion_slide_guide/assets/11_식물학_과학_일러스트_스타일_2.png"],category:"교육 & 스케치"},
  {num:24,title:"스케치노트 스타일",prompt:"Sketch notebook style, hand-drawn aesthetic, doodle art, personal notebook feel, warm paper texture, casual friendly vibe",images:["notion_slide_guide/assets/24_스케치노트_스타일_1.png","notion_slide_guide/assets/24_스케치노트_스타일_2.png"],category:"교육 & 스케치"},
  {num:38,title:"핸드드로잉 노트북 필기",prompt:"Hand-drawn notebook scribble, personal note taking, messy notebook aesthetic, organic hand writing, warm personal journal feel",images:["notion_slide_guide/assets/38_핸드드로잉_노트북_필기_1.png","notion_slide_guide/assets/38_핸드드로잉_노트북_필기_2.png"],category:"교육 & 스케치"},
  {num:41,title:"스텝 바이 스텝 매뉴얼",prompt:"Step by step manual, instructional guide visual, tutorial layout, how-to documentation, educational step sequence, clear process flow",images:["notion_slide_guide/assets/41_스텝_바이_스텝_매뉴얼_1.png","notion_slide_guide/assets/41_스텝_바이_스텝_매뉴얼_2.png"],category:"교육 & 스케치"},
  
  // 레트로 & 클래식 (16-25)
  {num:7,title:"네온/사이버 펑크 스타일",prompt:"Neon noir technological scene, cyberpunk aesthetic, dark background with glowing neon accents, glowing data streams, highly detailed, futuristic",images:["notion_slide_guide/assets/07_네온_사이버_펑크_스타일_1.png","notion_slide_guide/assets/07_네온_사이버_펑크_스타일_2.png"],category:"레트로 & 클래식"},
  {num:8,title:"도스 스타일(터미널, 녹색 텍스트)",prompt:"Retro CRT monitor screen, Matrix green text on black background, glowing phosphor, terminal code, vintage hacker aesthetic, scanlines",images:["notion_slide_guide/assets/08_도스_스타일_터미널_녹색_텍스트_1.png","notion_slide_guide/assets/08_도스_스타일_터미널_녹색_텍스트_2.png"],category:"레트로 & 클래식"},
  {num:13,title:"레트로 팝 스타일",prompt:"Retro pop art, playful aesthetic, 1980s Memphis design, bold outlines, vibrant flat colors, dynamic composition, energetic",images:["notion_slide_guide/assets/13_레트로_팝_스타일_1.png","notion_slide_guide/assets/13_레트로_팝_스타일_2.png"],category:"레트로 & 클래식"},
  {num:14,title:"빈티지/액션 코믹스 스타일",prompt:"Vintage comic book style, bold halftone dots, 1950s comic aesthetic, vibrant retro colors, dynamic action poses, illustrative",images:["notion_slide_guide/assets/14_빈티지_액션_코믹스_스타일_1.png","notion_slide_guide/assets/14_빈티지_액션_코믹스_스타일_2.png"],category:"레트로 & 클래식"},
  {num:15,title:"레트로 코믹 액션 블루프린트",prompt:"Retro comic action blueprint, vintage technical drawing aesthetic, bold outlines, halftone shading, dynamic comic composition",images:["notion_slide_guide/assets/15_레트로_코믹_액션_블루프린트_1.png","notion_slide_guide/assets/15_레트로_코믹_액션_블루프린트_2.png"],category:"레트로 & 클래식"},
  {num:17,title:"로코코(프랑스, 낭만적) 스타일",prompt:"Rococo decorative style, French romantic aesthetic, ornate pastel details, elegant gilded frames, whimsical cherubs, soft romantic lighting",images:["notion_slide_guide/assets/17_로코코_프랑스_낭만적_스타일_1.png","notion_slide_guide/assets/17_로코코_프랑스_낭만적_스타일_2.png"],category:"레트로 & 클래식"},
  {num:25,title:"그라디언트 모던 커버",prompt:"Modern gradient cover, smooth color transitions, contemporary abstract design, premium aesthetic, social media ready, vibrant yet elegant",images:["notion_slide_guide/assets/25_그라디언트_모던_커버_1.png","notion_slide_guide/assets/25_그라디언트_모던_커버_2.png"],category:"레트로 & 클래식"},
  {num:26,title:"도트 픽셀 아트 2D",prompt:"Dot pixel art 2D, retro gaming aesthetic, 8-bit style, pixelated characters, nostalgic computer graphics, vintage game visuals",images:["notion_slide_guide/assets/26_도트_픽셀_아트_2D_1.png","notion_slide_guide/assets/26_도트_픽셀_아트_2D_2.png"],category:"레트로 & 클래식"},
  
  // 3D & 아이소메트릭 (26-35)
  {num:9,title:"복셀(3차원 픽셀) 아트 스타일",prompt:"Isometric voxel art, gamified office environment, highly detailed blocks, bright lighting, colorful pixel 3D, cute architectural diagram --ar 16:9",images:["notion_slide_guide/assets/09_복셀_3차원_픽셀_아트_스타일_1.png","notion_slide_guide/assets/09_복셀_3차원_픽셀_아트_스타일_2.png"],category:"3D & 아이소메트릭"},
  {num:10,title:"클레이 애니메이션 스타일",prompt:"Claymation style, tactile 3D illustration, cute office worker figurine, soft smooth lighting, playful stop-motion aesthetic, vibrant pastel colors",images:["notion_slide_guide/assets/10_클레이_애니메이션_스타일_1.png","notion_slide_guide/assets/10_클레이_애니메이션_스타일_2.png"],category:"3D & 아이소메트릭"},
  {num:16,title:"역동적(하이 옥탄) 스타일 애니메이션",prompt:"High octane dynamic animation style, explosive energy, fast-paced action sequences, dramatic camera angles, vibrant motion blur",images:["notion_slide_guide/assets/16_역동적_하이_옥탄_스타일_애니메이션_1.png","notion_slide_guide/assets/16_역동적_하이_옥탄_스타일_애니메이션_2.png"],category:"3D & 아이소메트릭"},
  {num:19,title:"글래스 모피즘 3D (투명) 스타일",prompt:"Glassmorphism 3D style, translucent frosted glass effect, vibrant colorful backgrounds, soft shadows, modern UI aesthetic, premium glass surfaces",images:["notion_slide_guide/assets/19_글래스_모피즘_3D_투명_스타일_1.png","notion_slide_guide/assets/19_글래스_모피즘_3D_투명_스타일_2.png"],category:"3D & 아이소메트릭"},
  {num:20,title:"페이퍼 컷아웃 아트 스타일",prompt:"Paper cutout art, layered paper craft, delicate paper textures, hand-crafted aesthetic, whimsical layered design, subtle shadows",images:["notion_slide_guide/assets/20_페이퍼_컷아웃_아트_스타일_1.png","notion_slide_guide/assets/20_페이퍼_컷아웃_아트_스타일_2.png"],category:"3D & 아이소메트릭"},
  {num:39,title:"아이소메트릭 플랫 인포그래픽",prompt:"Isometric flat infographic, 2.5D illustration style, clean geometric design, data visualization, technical presentation aesthetic",images:["notion_slide_guide/assets/39_아이소메트릭_플랫_인포그래픽_1.png","notion_slide_guide/assets/39_아이소메트릭_플랫_인포그래픽_2.png"],category:"3D & 아이소메트릭"},
  {num:42,title:"3D 아이소메트릭 비즈니스 스타일",prompt:"3D isometric business style, corporate isometric illustration, professional 3D aesthetic, business scene visualization, modern corporate design",images:["notion_slide_guide/assets/42_3D_아이소메트릭_비즈니스_스타일_1.png","notion_slide_guide/assets/42_3D_아이소메트릭_비즈니스_스타일_2.png"],category:"3D & 아이소메트릭"},
  
  // 비즈니스 & 데이터 (36-49)
  {num:6,title:"바우하우스(현대 건축, 현대 미술) 스타일",prompt:"Bauhaus aesthetic, geometric abstraction, primary colors (red, blue, yellow), strict grid, modern minimalist poster, clean typography layout",images:["notion_slide_guide/assets/06_바우하우스_현대_건축_현대_미술_스타일_1.png","notion_slide_guide/assets/06_바우하우스_현대_건축_현대_미술_스타일_2.png"],category:"비즈니스 & 데이터"},
  {num:12,title:"카와이 스타일 / 파스텔 톤",prompt:"Kawaii illustration, girly pastel colors, soft and fluffy aesthetic, cute minimalist characters, warm lighting, dreamlike",images:["notion_slide_guide/assets/12_카와이_스타일_파스텔_톤_1.png","notion_slide_guide/assets/12_카와이_스타일_파스텔_톤_2.png"],category:"비즈니스 & 데이터"},
  {num:21,title:"플랫 벡터 모션그래픽 스타일",prompt:"Flat vector motion graphics, science channel aesthetic, vibrant deep space colors, clean minimalist background, educational infographic, highly detailed yet simplified --ar 16:9",images:["notion_slide_guide/assets/21_플랫_벡터_모션그래픽_스타일_1.png","notion_slide_guide/assets/21_플랫_벡터_모션그래픽_스타일_2.png"],category:"비즈니스 & 데이터"},
  {num:22,title:"시네마틱 우주 SF 다큐멘터리 스타일",prompt:"Cinematic space documentary, NASA footage aesthetic, realistic planets, nebula backgrounds, dramatic cosmic lighting, educational science documentary",images:["notion_slide_guide/assets/22_시네마틱_우주_SF_다큐멘터리_스타일_1.png","notion_slide_guide/assets/22_시네마틱_우주_SF_다큐멘터리_스타일_2.png"],category:"비즈니스 & 데이터"},
  {num:23,title:"뉴스레터 에디토리얼",prompt:"Newsletter editorial design, clean typographic layout, modern magazine aesthetic, bold headlines, readable body text, professional print design",images:["notion_slide_guide/assets/23_뉴스레터_에디토리얼_1.png","notion_slide_guide/assets/23_뉴스레터_에디토리얼_2.png"],category:"비즈니스 & 데이터"},
  {num:28,title:"Before / After 비교 카드형",prompt:"Before and after comparison cards, side by side layout, transformation visual, clean comparison design, progress visualization, impactful contrast",images:["notion_slide_guide/assets/28_Before_After_비교_카드형_1.png","notion_slide_guide/assets/28_Before_After_비교_카드형_2.png"],category:"비즈니스 & 데이터"},
  {num:29,title:"화이트보드 전략 회의형 스타일",prompt:"Whiteboard strategy meeting, collaborative planning visual, sticky notes, marker sketches, team brainstorming aesthetic, strategic planning diagram",images:["notion_slide_guide/assets/29_화이트보드_전략_회의형_스타일_1.png","notion_slide_guide/assets/29_화이트보드_전략_회의형_스타일_2.png"],category:"비즈니스 & 데이터"},
  {num:30,title:"카드 뉴스형 정보 요약",prompt:"Card news information summary, news card layout, bite-sized information, visual hierarchy, news app aesthetic, quick scan readability",images:["notion_slide_guide/assets/30_카드_뉴스형_정보_요약_1.png","notion_slide_guide/assets/30_카드_뉴스형_정보_요약_2.png"],category:"비즈니스 & 데이터"},
  {num:31,title:"서류 / 리서치 데스크 스타일",prompt:"Research desk aesthetic, document collection, reference papers, academic research visual, organized desk setup, scholarly environment",images:["notion_slide_guide/assets/31_서류_리서치_데스크_스타일_1.png","notion_slide_guide/assets/31_서류_리서치_데스크_스타일_2.png"],category:"비즈니스 & 데이터"},
  {num:32,title:"데이터 스토리텔링/광고 포스터",prompt:"Data storytelling advertisement poster, compelling narrative visual, advertising design, emotional impact, marketing campaign aesthetic, data-driven storytelling",images:["notion_slide_guide/assets/32_데이터_스토리텔링_광고_포스터_1.png","notion_slide_guide/assets/32_데이터_스토리텔링_광고_포스터_2.png"],category:"비즈니스 & 데이터"},
  {num:34,title:"협업툴 메시지형 비주얼",prompt:"Collaboration tool messaging visual, Slack Teams style, chat interface aesthetic, team communication design, modern messaging UI",images:["notion_slide_guide/assets/34_협업툴_메시지형_비주얼_1.png","notion_slide_guide/assets/34_협업툴_메시지형_비주얼_2.png"],category:"비즈니스 & 데이터"},
  {num:35,title:"포스트잇 문제 해결 맵",prompt:"Post-it problem solving map, sticky note analysis, issue tracking visual, collaborative problem solving, office whiteboard aesthetic",images:["notion_slide_guide/assets/35_포스트잇_문제_해결_맵_1.png","notion_slide_guide/assets/35_포스트잇_문제_해결_맵_2.png"],category:"비즈니스 & 데이터"},
  {num:36,title:"미니멀 라인 아트 다이어그램",prompt:"Minimal line art diagram, clean line drawing, simple geometric shapes, monochrome aesthetic, technical illustration style, elegant minimal design",images:["notion_slide_guide/assets/36_미니멀_라인_아트_다이어그램_1.png","notion_slide_guide/assets/36_미니멀_라인_아트_다이어그램_2.png"],category:"비즈니스 & 데이터"},
  {num:37,title:"프리미엄 스톡 사진",prompt:"Premium stock photography style, high-quality professional photo, commercial advertising aesthetic, clean and polished visual, corporate marketing material",images:["notion_slide_guide/assets/37_프리미엄_스톡_사진_1.png","notion_slide_guide/assets/37_프리미엄_스톡_사진_2.png"],category:"비즈니스 & 데이터"},
  {num:40,title:"듀오톤 그래픽 스타일",prompt:"Duotone graphic style, two-tone color scheme, bold contrast design, poster aesthetic, striking duotone visuals, dramatic color impact",images:["notion_slide_guide/assets/40_듀오톤_그래픽_스타일_1.png","notion_slide_guide/assets/40_듀오톤_그래픽_스타일_2.png"],category:"비즈니스 & 데이터"},
  {num:44,title:"디지털 마인드맵 / 노드 스타일",prompt:"Digital mind map node style, connected network visualization, information architecture, node graph design, data mapping aesthetic",images:["notion_slide_guide/assets/44_디지털_마인드맵_노드_스타일_1.png","notion_slide_guide/assets/44_디지털_마인드맵_노드_스타일_2.png"],category:"비즈니스 & 데이터"},
  {num:45,title:"볼드 타이포그래피",prompt:"Bold typography design, strong typographic statement, impactful text visual, expressive letterforms, dramatic type composition, headline focused design",images:["notion_slide_guide/assets/45_볼드_타이포그래피_1.png","notion_slide_guide/assets/45_볼드_타이포그래피_2.png"],category:"비즈니스 & 데이터"},
  {num:46,title:"폴라로이드 무드보드",prompt:"Polaroid moodboard, photo collage aesthetic, instant film style, personal mood collection, warm nostalgic visual, scrapbook aesthetic",images:["notion_slide_guide/assets/46_폴라로이드_무드보드_1.png","notion_slide_guide/assets/46_폴라로이드_무드보드_2.png"],category:"비즈니스 & 데이터"},
  {num:47,title:"디지털 태블릿 다이어리",prompt:"Digital tablet diary, iPad note taking aesthetic, digital journaling, handwritten digital notes, modern note app visual, personal digital diary",images:["notion_slide_guide/assets/47_디지털_태블릿_다이어리_1.png","notion_slide_guide/assets/47_디지털_태블릿_다이어리_2.png"],category:"비즈니스 & 데이터"},
];
